### PR TITLE
Issue 87: Problem finding logback.xml

### LINKED ISSUE #87: Problem finding logback.xml in Pravega example applications
**Problem description**
After executing `./gradlew installDist`, running in a terminal any of the generated executable example applications prints the following exception:

```
Failed to auto configure default logger context
Reported exception:
ch.qos.logback.core.joran.spi.JoranException: Could not open URL [file:conf/logback.xml].
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:57)
	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at ch.qos.logback.classic.util.ContextInitializer.autoConfig(ContextInitializer.java:150)
	at org.slf4j.impl.StaticLoggerBinder.init(StaticLoggerBinder.java:84)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:55)
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at io.pravega.client.ClientConfig.<clinit>(ClientConfig.java:32)
	at io.pravega.client.ClientFactory.withScope(ClientFactory.java:65)
	at io.pravega.example.statesynchronizer.SharedConfigCli.<init>(SharedConfigCli.java:66)
	at io.pravega.example.statesynchronizer.SharedConfigCli.main(SharedConfigCli.java:385)
Caused by: java.io.FileNotFoundException: conf/logback.xml (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:52)
	... 13 more
```
Despite the user can proceed with the example application, the error behind this exception should be solved. In my setting, this does not happen when applications are executed via the IDE (IntelliJ).

**Problem location**
This is probably due to a bad configuration of logfile.xml location when gradle builds the executable files. 

**Suggestions for an improvement**
Proper configuration of logback.xml when gradle creates the executable files.

### PR DESCRIPTION
**Pull request by RaulGracia**
**Change log description**
Changed the `build.gradle` file of `pravega-client-examples` and `scenarios/turbine-heat-sensor` to correctly point to the packaged `logback.xml` file.

**Purpose of the change**
Fixes #87.

**What the code does**
The code just deletes the `file:` prefix in `build.gradle` which was apparently preventing the execution script to find the `logback.xml` file. This PR also deletes two `TODOs` related to this issue in `ConsoleReader.java`: as before, we output each read event to both to the user via console and to the log. Otherwise, showing read events to the user would require to write in the console log entries for `INFO` level, which is excessive and may be confusing for the user.

**How to verify it**
Build `pravega-client-examples` and `scenarios/turbine-heat-sensor` and execute the applications. There should not be any exception as the one reported in the issue.

### CODE REVIEW

**Comment by EronWright** [comment]
I'm suspicious here; maybe we'd be breaking one scenario to make another work.   Would you please describe the apparent behavior prior to this PR?

**Comment by RaulGracia** [comment]
The problem addressed in the PR is described in detail in #87; in summary, all the applications using `logback.xml` were not able to find it. I have been investigating and, as far as I know, adding the `file:` prefix refers to look for a file system location (e.g., /conf/logback.xml). Instead, without the `file:` prefix, the logging library looks for the file within the classpath (included by the build script). To understand this in depth, I printed the classpath in gradle and I found:
```...
../../../../../../.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-api/1.7.25/da76ca59f6a57ee3102f8f9bd9cee742973efa8a/slf4j-api-1.7.25.jar
build/classes/java/main
build/libs/pravega-client-scenario-turbineheatsensor-0.3.0-SNAPSHOT.jar
build/resources/main (here is were logback.xml file is)
```

The last entry is the location of the `logback.xml`, so only specifying the name of that file is enough for the application to find it. I also tested to add another configuration file (`logback2.xml`), and just changing `-Dlogback.configurationFile=logback.xml` by `-Dlogback.configurationFile=logback2.xml` in gradle the application correctly gets the configuration file.

I tested all the applications involved after this change and all of them work in my VM without throwing the exception described in the issue.

**Comment by RaulGracia** [comment]
In summary, this PR allows users to execute pravega samples from any location without getting the `logback.xml` location error (now it only works if the user is located in the directory where the gradle output is generated). Although we can expect from users to strictly follow the instructions and execute the samples from a specific location, this may not be always the case. This PR can avoid the `logback.xml` exception in those cases in which users do not execute the script from the right location. However, the downside is that we lose flexibility as the `logback.xml` used is part of the generated `jar` and cannot be changed across runs (we need to rebuild the application). That said, I leave the decision of closing or merging this PR up to you (@vijikarthi, @EronWright, @fpj).

**Comment by vijikarthi** [comment]
We could drop this PR since the expected way to run the application is from the `install/<PROEJCT>` directory. In that case, the log configuration should be visible from `install/<PROEJCT>/conf` location.

**Comment by EronWright** [comment]
Thanks @RaulGracia for putting in the effort, but I think we've opted to stick to the status quo for now.

**Pull request closed without merging**
