### PR TITLE
Issue 269: Update PySpark example to work with Python 2

### PR DESCRIPTION
**Pull request by claudiofahey**
- Update PySpark example to work with Python 2
- Specify spark-connectors branch to use for examples
- Fix examples project version number
Signed-off-by: Claudio Fahey <claudio.fahey@dell.com>

### CODE REVIEW

**Review by crazyzhou — CHANGES_REQUESTED** [review]
As we released our first version of spark connector, it's now possible to simplify the whole process to use the 0.9.0 connector artifacts from maven central.

**Comment by claudiofahey** [comment]
> As we released our first version of spark connector, it's now possible to simplify the whole process to use the 0.9.0 connector artifacts from maven central.

This is a good idea and I have now done this in https://github.com/pravega/pravega-samples/pull/287. The current PR adds a 1 line change to that PR to allow it to work with Python 2.

**Review by crazyzhou — COMMENTED** [review]
Is this superseded by #287 ?

**Comment by claudiofahey** [comment]
> Is this superseded by #287 ?

No. This PR depends on #284 and #287. We should merge in this order: #284, #287, #270.

**Review by crazyzhou — APPROVED** [review]
LGTM

**Pull request merged**
